### ISSUE TITLE
Issue with importing library

### ISSUE THREAD

**Issue by mpoleszczyk** [KevinHonka/Icinga2_Python_API#2]
My script is following

import icinga2

icinga2api = Icinga2API(username = "myuser", password = "mypass", url = "http://my-url", debug = False)

I'm getting error from __init__.py

[root@euca-10-254-48-13 tmp]# python3 test_icinga.py 
Traceback (most recent call last):
  File "test_icinga.py", line 1, in <module>
    import icinga2
  File "/usr/lib/python3.4/site-packages/icinga2-0.3-py3.4.egg/icinga2/__init__.py", line 1, in <module>
ImportError: cannot import name 'Icinga2API'

**Comment by KevinHonka** [comment]
Will take a look at it, please note that I only tested it on python 2.7

**Comment by KevinHonka** [comment]
fixed with commit: 147a953e27363d5c242ee4e7859eebd047293508

**Comment by mpoleszczyk** [comment]
Hi,
Will you upload new version to pypi ?
